FROM python:3.9-slim
RUN apt-get update && apt-get install -y default-jre && apt-get clean
WORKDIR /app
COPY requirements.txt .
COPY athletes.csv .
COPY h2o_automl.py .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "h2o_automl.py"]
